version: '3.8'

services:
  arqo-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: arqo-backend
    restart: unless-stopped
    ports:
      - "1337:1337"
    environment:
      - HOST=0.0.0.0
      - PORT=1337
      - APP_KEYS=toBeModified1,toBeModified2
      - API_TOKEN_SALT=toBeModified3
      - ADMIN_JWT_SECRET=toBeModified4
      - TRANSFER_TOKEN_SALT=toBeModified5
      - JWT_SECRET=toBeModified6
      # Если вы хотите, чтобы база не перезаписывалась сидом при каждом старте:
      # - SKIP_SEED=true
    volumes:
      # Сохраняем базу данных и загруженные картинки на сервере
      - ./backend_data/.tmp:/app/.tmp
      - ./backend_data/uploads:/app/public/uploads

  arqo-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        # При сборке на сервере сюда нужно будет подставить IP вашего сервера
        - NEXT_PUBLIC_STRAPI_API_URL=${NEXT_PUBLIC_STRAPI_API_URL:-http://45.146.164.46:1337}
    container_name: arqo-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_STRAPI_API_URL=${NEXT_PUBLIC_STRAPI_API_URL:-http://45.146.164.46:1337}
    depends_on:
      - arqo-backend
